// frontend/src/app/components/chat/chat.component.ts
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ChatService } from '../../services/chat.service';

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './chat.component.html',
  styleUrl: './chat.component.css'
})
export class ChatComponent {
  userQuery = ''; 
  
  responseBuffer = signal<string>(''); 
  isLoading = signal<boolean>(false);

  constructor(private chatService: ChatService) {}

  async send() {
    if (!this.userQuery.trim()) return;

    this.responseBuffer.set('');
    this.isLoading.set(true);
    
    const queryToSend = this.userQuery;

    try {
      await this.chatService.sendMessage(queryToSend, (chunk) => {
        this.responseBuffer.update(old => old + chunk);
      });
    } catch (error) {
      console.error('Erro no chat:', error);
      this.responseBuffer.set('Erro ao conectar com o servidor.');
    } finally {
      this.isLoading.set(false);
    }
  }
}

<div class="input-group">
  <input 
    type="text" 
    class="chat-input"
    [(ngModel)]="userQuery" 
    (keyup.enter)="send()"
    placeholder="Pergunte algo sobre seus documentos..." 
    [disabled]="isLoading()"
  >
  <button 
    class="send-button"
    (click)="send()" 
    [disabled]="isLoading() || !userQuery.trim()"
  >
    @if (isLoading()) {
      <span>Gerando...</span>
    } @else {
      <span>Enviar</span>
    }
  </button>
</div>

@if (responseBuffer()) {
  <div class="response-area">
    <h3 class="response-title">Resposta:</h3>
    <pre class="response-text">{{ responseBuffer() }}</pre>
  </div>
}

// frontend/src/components/Chat.tsx
"use client";
import { useState } from 'react';
import { sendMessage } from '../services/api';

export default function Chat() {
  const [userQuery, setUserQuery] = useState('');
  const [response, setResponse] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSend = async () => {
    if (!userQuery.trim()) return;

    setIsLoading(true);
    setResponse('');

    try {
      await sendMessage(userQuery, (chunk) => {
        setResponse((prev) => prev + chunk);
      });
    } catch (error) {
      console.error(error);
      setResponse('Erro ao conectar com o servidor.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="w-full max-w-2xl mx-auto p-4">
      {/* Área de Input */}
      <div className="flex gap-2 mb-6">
        <input
          type="text"
          className="flex-1 p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-black"
          placeholder="Pergunte algo sobre seus documentos..."
          value={userQuery}
          onChange={(e) => setUserQuery(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSend()}
          disabled={isLoading}
        />
        <button
          onClick={handleSend}
          disabled={isLoading || !userQuery.trim()}
          className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-400 transition-colors font-medium"
        >
          {isLoading ? 'Gerando...' : 'Enviar'}
        </button>
      </div>

      {/* Área de Resposta */}
      {response && (
        <div className="bg-gray-50 border border-gray-200 rounded-xl p-6 shadow-sm">
          <h3 className="text-gray-700 font-bold mb-2">Resposta:</h3>
          <p className="whitespace-pre-wrap text-gray-800 leading-relaxed">
            {response}
          </p>
        </div>
      )}
    </div>
  );
}
