// frontend/src/components/FileUpload.tsx
"use client";
import { useState } from 'react';
import { uploadFile } from '../services/api';

export default function FileUpload() {
  const [isUploading, setIsUploading] = useState(false);
  const [status, setStatus] = useState('');

  const handleFileSelected = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    setStatus(`Enviando ${file.name}...`);

    try {
      const result = await uploadFile(file);
      setStatus(`✅ Sucesso! ${result.chunks} trechos indexados.`);
    } catch (error) {
      console.error(error);
      setStatus('❌ Erro ao enviar arquivo.');
    } finally {
      setIsUploading(false);
      event.target.value = '';
    }
  };

  return (
    <div className="w-full max-w-2xl mx-auto p-4 flex flex-col items-center gap-4">
      <label className={`
        flex items-center gap-2 px-6 py-3 rounded-full cursor-pointer transition-all shadow-sm border
        ${isUploading 
          ? 'bg-gray-100 text-gray-500 border-gray-300 cursor-not-allowed' 
          : 'bg-white hover:bg-gray-50 text-blue-600 border-blue-200 hover:border-blue-400'}
      `}>
        <input 
          type="file" 
          accept=".pdf" 
          onChange={handleFileSelected} 
          disabled={isUploading} 
          className="hidden" 
        />
        <span className="font-medium">
          {isUploading ? '⏳ Processando PDF...' : '📎 Adicionar PDF ao RAG'}
        </span>
      </label>

      {status && (
        <div className="text-sm font-medium text-gray-600 animate-pulse">
          {status}
        </div>
      )}
    </div>
  );
}

// frontend/src/app/components/file-upload/file-upload.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ChatService } from '../../services/chat.service';

@Component({
  selector: 'app-file-upload',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './file-upload.component.html',
  styleUrl: './file-upload.component.css'
})
export class FileUploadComponent {
  isUploading = signal(false);
  uploadStatus = signal<string>('');

  constructor(private chatService: ChatService) {}

  async onFileSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    if (!input.files?.length) return;

    const file = input.files[0];
    this.isUploading.set(true);
    this.uploadStatus.set(`Enviando ${file.name}...`);

    try {
      const result = await this.chatService.uploadFile(file);
      this.uploadStatus.set(`✅ Sucesso! ${result.chunks} trechos indexados.`);
    } catch (error) {
      this.uploadStatus.set('❌ Erro ao enviar arquivo.');
      console.error(error);
    } finally {
      this.isUploading.set(false);
      input.value = ''; // Limpar input
    }
  }
}

<div class="upload-container">
  <label class="upload-btn" [class.disabled]="isUploading()">
    <input type="file" accept=".pdf" (change)="onFileSelected($event)" [disabled]="isUploading()">
    <span>
      @if (isUploading()) {
        ⏳ Enviando...
      } @else {
        📎 Adicionar PDF
      }
    </span>
  </label>
  
  @if (uploadStatus()) {
    <div class="status-message">
      {{ uploadStatus() }}
    </div>
  }
</div>
